.github/workflows/main.yml, CHANGELOG.md, README.md, examples/metrics/README.md, examples/metrics/requirements.txt, examples/metrics/run.py, gantry/__init__.py, gantry/__main__.py, gantry/common/constants.py, gantry/exceptions.py, tests/main_test.py
=> Add metrics example, add `--yes` flag, allow non-private workspaces but ask to confirm

CHANGELOG.md, gantry/common/constants.py, gantry/entrypoint.sh
=> Fix issue with non-empty working directory

CHANGELOG.md, gantry/__main__.py, gantry/common/util.py
Closes #21
@csarron can you confirm that this works for you?
=> Add `--env` and `--env-secret` options

CHANGELOG.md, gantry/common/constants.py, gantry/common/util.py
Fixes NFS location bug introduced in #54
Changes proposed in this pull request:
- Replace `/net/nfs` with `/net/nfs.cirrascale`. The former doesn't actually work for nfs, tested [here](https://beaker.org/ex/01GS634EY28A8P6D7R8P5S0Q34/tasks/01GS634EZES1BX8NJ8DND82Y19/job/01GS634S4SF24HC108KK6J2RDY). I have tested that using `/net/nfs.cirrascale` instead works [here](https://beaker.org/ex/01GS64801CBXAK5FVVGHYVCF4R/tasks/01GS648031C6DHVNGAC8XH4CG0/job/01GS6482J7KGAW40GG21G45SVS).
section of the `CONTRIBUTING` docs.
[Writing docstrings](https://github.com/allenai/beaker-py/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
=> Fix nfs location

CHANGELOG.md, README.md, gantry/entrypoint.sh
=> install conda on container when not found

CHANGELOG.md, README.md, gantry/__main__.py, gantry/entrypoint.sh, gantry/util.py
=> Don't require a GitHub PAT for public repos

CHANGELOG.md, gantry/__main__.py, gantry/util.py
E.g.
```bash
gantry run ... --dataset 'foobar:sub/path:/mount/location'
```
=> add support for subpaths when attaching datasets

CHANGELOG.md, gantry/__main__.py, gantry/util.py
Adds `--hostname` option for adding hostname constraints.
FYI @piperwolters, @mewil
=> add hostname constraint

.github/workflows/main.yml, CHANGELOG.md, gantry/__main__.py, gantry/util.py, pyproject.toml
- **Don't prompt for name if `--yes`**
- **expand cluster functionality**
=> Add more flags and commands

CHANGELOG.md, gantry/entrypoint.sh
Automatically clone git submodules.
=> Automatically clone submodules

CHANGELOG.md, gantry/commands/follow.py, gantry/commands/stop.py, gantry/util.py, pyproject.toml
- Add confirmation prompt to `stop` command.
- Add several options to `follow` command.
=> Improve `stop` and `follow commands`

.github/workflows/main.yml, CHANGELOG.md, gantry/entrypoint.sh, gantry/util.py
=> Make conda install optional

CHANGELOG.md, gantry/commands/run.py, gantry/entrypoint.sh
=> Add `--no-conda` flag

CHANGELOG.md, gantry/commands/run.py
=> Add `--dataset-secret` option

.github/workflows/main.yml, CHANGELOG.md, gantry/commands/run.py, gantry/exceptions.py, gantry/util.py
=> Ensure ref exists on remote

.github/actions/setup-venv/action.yml, CHANGELOG.md, gantry/commands/run.py
=> Add `--not-preemptible` option

CHANGELOG.md, conftest.py, gantry/commands/run.py, tests/commands/run_test.py
We were trying to iterate over a 1-time generator multiple times.
=> Fix bug when specifying multiple clusters

CHANGELOG.md, gantry/commands/list.py, gantry/commands/main.py, gantry/commands/open.py, gantry/commands/run.py, gantry/util.py, pyproject.toml
Adds support for grouping runs with Beaker Groups.
=> Add `--group` option to `gantry run` and `gantry list`

CHANGELOG.md, gantry/api.py, gantry/commands/run.py, tests/commands/run_test.py
E.g. `gantry run --tag='storage:weka' -- echo "Hello, World"`
=> Add support for choosing clusters based on tags

CHANGELOG.md, gantry/entrypoint.sh
Following https://stackoverflow.com/a/43136160.
=> shallow clone single commit
